version: '3.8'

services:
  simplecrudapi:
    image: simplecrudapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5250:5250

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password.123456"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d  # Montar un volumen local que contiene scripts SQL
    command: "--attach-database /docker-entrypoint-initdb.d/master.mdf --sa-password Password.123456"

volumes:
  sqlserver_data: